1 implement account registration page
jrs-coding-school/winter-2023-group-project pull request #31
Opened 2023-03-15 23:54 UTC by im-addie

- created a login page for users to register an account
- routes users back to the homepage if their registration was successful
- shows an error if the user doesn't meet input requirements

2023-03-16 15:16 UTC, Amin-JRS requested changes
make changes before approval

2023-03-16 15:16 UTC, Amin-JRS commented on api/migrations/20230315172305_user.js
Remove migration file

2023-03-16 15:16 UTC, Amin-JRS commented on ui/src/views/Register/index.js
On successful registration run `setToken(token)` from utils.js before routing to the home page. This will sign-in the user.

2023-03-16 20:32 UTC, im-addie commented
Requested changes have been resolved.

2023-03-17 14:44 UTC, Amin-JRS approved these changes

2023-03-17 14:45 UTC, merged